import React from "react";
import Head from "next/head";
import Layout from "../../components/layout";

const Player02 = () => {
  const videoObjectSrc = "../videos/celebration-video-2210230206.mp4";

  return (
    <div>
      <Head>
        <title>1Q WEDDING</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/hana-1q-logo-0.png" />
      </Head>
      <Layout>
        <div className="bg-teal-800 h-[40rem] flex justify-center items-center">
          <div className="flex justify-center mx-20 py-20">
            <div className="flex-col items-center place-items-center">
              <div className="max-w-3xl">
                <video
                  playsInline
                  controls
                  // loop
                  // muted
                  poster="../hana-3d-logo.png"
                  className="rounded-xl bg-gray-900"
                >
                  <source src={videoObjectSrc} type="video/mp4" />
                  Your browser does not support the video tag.
                </video>
              </div>
            </div>
          </div>
        </div>
      </Layout>
    </div>
  );
};

export default Player02;
