import Head from "next/head";
import Layout from "../components/layout";
import Intro from "./sections/intro";
import Main from "./sections/main";
import Viewer from "./sections/viewer";
import Chart from "./sections/chart";
import Intro1 from "./sections/intro-1";
import Intro2 from "./sections/intro-2";
import Intro3 from "./sections/intro-3";
import Intro4 from "./sections/intro-4";

export default function Home() {
  return (
    <div>
      <Head>
        <title>1Q WEDDING</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/hana-1q-logo-0.png" />
      </Head>
      <Layout>
        <Main />
        {/* <Intro />
        <Viewer /> */}
        {/* <Chart /> */}
        <Intro1 />
        <Intro2 />
        <Intro3 />
        <Intro4 />
      </Layout>
    </div>
  );
}
