import Head from "next/head";
import Layout from "../components/layout";
import About from "./sections/about";

export default function Welcome() {
  return (
    <div>
      <Head>
        <title>1Q WEDDING</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/hana-1q-logo-0.png" />
      </Head>
      <Layout>
        <About />
        {/* <Intro />
        <Viewer /> */}
        {/* <Chart /> */}
      </Layout>
    </div>
  );
}
